Update yaml to work with latest version of vmdb2
* Update vmdb2 to master in order to fix errors like this:

  > ERROR: No runner implements step with keys fs-type, start,
  > mkpart, part-tag, end, device

* I found that I had to add a `kpartx` step, which was hinted at in
  the `kpartx` section in `partition.mdwn`:

  > Create loop devices for partitions in an image file. Not needed
  > when installing to a real block device, instead of an image
  > file.

* I found from reading the source code that the `part-tag` and
  `fs-tag` keys had been renamed to `tag`, and so I updated the yaml
  file accordingly.

Fixes #47.